use_frameworks!

platform :ios, '8.0'

target 'YYLTestLib_Example' do
  pod 'YYLTestLib', :path => '../'

  target 'YYLTestLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
